---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-udp-client
  labels:
    app: single-udp-client
spec:
  replicas: 1
  template:
    metadata:
      name: single-udp-client
      labels:
        app: single-udp-client
    spec:
      containers:
        - name: single-udp-client
          image: lnanjangud653/singleudpclient:1.0
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
              protocol: UDP
      restartPolicy: Always
  selector:
    matchLabels:
      app: single-udp-client
---