FROM ubuntu:18.04

LABEL Developer="Lakshya Nanjangud <lnanjangud@vmware.com>"

LABEL Maintainer="Solution Engineering Team - TKG(MAPBU)"

WORKDIR /usr/src/app

EXPOSE 7000

COPY singleudpserver .

# CMD "./udpserver"