FROM photon:4.0

LABEL Developer="Lakshya Nanjangud <lnanjangud@vmware.com>"

LABEL Maintainer="Solution Engineering Team - TKG(MAPBU)"

EXPOSE 10001/udp

WORKDIR /usr/src/app

COPY singleudpserver .

