---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conn-udp-client
  labels:
    app: conn-udp-client
spec:
  replicas: 1
  template:
    metadata:
      name: conn-udp-client
      labels:
        app: conn-udp-client
    spec:
      containers:
        - name: conn-udp-client
          image: lnanjangud653/udpclient:3.0
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: conn-udp-client
---